version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: clo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_crud_clo
      MYSQL_USER: user_crud_clo
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3308:3306"