version: '3.8'
services:
  jvg_db:
    image: mysql:8.0
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: jvg_db
      MYSQL_ROOT_USER: jvg_25
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jvg_25
      MYSQL_PASSWORD: root
    container_name: jvg_container
    restart: always